// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $DescriptionCollapse from "./islands/DescriptionCollapse.tsx";
import * as $ModalCoupon from "./islands/ModalCoupon.tsx";
import * as $PriceRangeSlider from "./islands/PriceRangeSlider.tsx";
import * as $ProductVideo from "./islands/ProductVideo.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
  },
  islands: {
    "./islands/DescriptionCollapse.tsx": $DescriptionCollapse,
    "./islands/ModalCoupon.tsx": $ModalCoupon,
    "./islands/PriceRangeSlider.tsx": $PriceRangeSlider,
    "./islands/ProductVideo.tsx": $ProductVideo,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
